remove compiser 3.0
due to this error

Running hidl-gen on vendor.qti.hardware.display.composer@3.0: ERROR: Unable to import 'android.hardware.graphics.composer@2.4::IComposer' at /datadrive/syb/vendor/qcom/opensource/interfaces/display/composer/3.0/IQtiComposer.hal:32.8-56
ERROR: Could not parse vendor.qti.hardware.display.composer@3.0::IQtiComposer. Aborting.
HIDL interfaces: Update Failed